### ISSUE TITLE
Tests probably shouldn't fail when test_key is not supported

### ISSUE THREAD

**Issue by pdimov** [boostorg/multi_index#15]
```
testing.capture-output bin.v2/libs/multi_index/test/test_key.test/gcc-4.8/debug/cxxstd-11-iso/test_key.run
====== BEGIN OUTPUT ======
libs/multi_index/test/test_key.cpp(22): test 'false' failed in function 'void test_key()'
1 error detected.
EXIT STATUS: 1
====== END OUTPUT ======
```

It would probably be better to use something like

```
#include <boost/config/pragma_message.hpp>

#if !defined(BOOST_MULTI_INDEX_KEY_SUPPORTED)

BOOST_PRAGMA_MESSAGE("Skipping test, boost::multi_index::key not supported")

void test_key()
{
}

#else
```

**Comment by joaquintides** [comment]
Hi Peter,

Thanks for the pointer! I'd like indeed to generate some warning rather than brutally fail, and had this in my to-investigate list. The problem I see with `BOOST_PRAGMA_MESSAGE` is that in many environments the test matrix shows green without attached messages, as evidenced in `pragma_message_test`.  Are you planning on improving this situation. I guess I'm looking for a `BOOST_PRAGMA_WARNING` of sorts.

**Comment by pdimov** [comment]
I don't think it's possible. The best that comes to mind is

```
#ifdef __GNUC__
# warning Skipping test, boost::multi_index::key not supported
#else
BOOST_PRAGMA_MESSAGE("Skipping test, boost::multi_index::key not supported")
#endif
```

**Comment by pdimov** [comment]
I see that you don't use Travis/Appveyor so it's probably not a big deal to just fail, but if you start, you'll see that it's much more convenient to let the test pass and keep it green. These integrate with Github and run on pull requests, so you can immediately estimate the quality of the submission.

I've rigged the Travis for boostorg/boost to run the tests on the library that's been updated, which is how I saw the above failure.

https://travis-ci.org/boostorg/boost/builds
https://travis-ci.org/boostorg/boost/builds/422173681

If you decide to set up Travis, you can look at the .travis.yml files for System or SmartPtr or Core or any of my libraries, they're fairly straightforward.

**Comment by joaquintides** [comment]
I've just done as you suggested:

https://github.com/boostorg/multi_index/commit/e86162cff82cea02d0f7482611081d488a90e305

As for Travis/AppVeyor support, I already included it in PolyCollection (and seem to recall I used your files as inspiration in the AppVeyor case), will do the same for MultiIndex and Flyweight when I find the time.

Thanks again

**Comment by joaquintides** [comment]
Additionally, I made `test_key` execution conditional on `BOOST_MULTI_INDEX_KEY_SUPPORTED` being defined:

https://github.com/boostorg/multi_index/blob/d6cd661119013386da240f745364b697e8fd240f/test/Jamfile.v2#L41-L45

which has the effect that the corresponding cell of the test matrix shows blank in pre-C++17 compilers.
