### ISSUE TITLE
Coverity static analysis defects (Trac ticket #13331)

### ISSUE THREAD

**Issue by mloskot** [boostorg/multi_index#16]
(copied from https://svn.boost.org/trac10/ticket/13331, only MultiIndex's parts from the attached report)

Boost 1.57.0

A static analysis tool called Coverity found medium and high defects in the boost source code. See attached file for defect type, defect category, filename and line number of defect.

Defect   Type | Defect Category | Line Number | Filename
-- | -- | -- | --
Uninitialized   pointer field | Uninitialized members | 990 | /boost/include/boost/multi_index/ordered_index.hpp

**Comment by joaquintides** [comment]
This was fixed some years ago at 08fe6a360acf99e1732a54ef8b3114455f59116b.
