### ISSUE TITLE
Use boost::swap instead of std::swap for swapping key/comp_ function objects

### ISSUE THREAD

**Issue by valziegler** [boostorg/multi_index#29]
void ordered_index_impl<...>::swap_(ordered_index_impl<...>& x) uses std::swap for swapping the key and comp_ functors. Is there any particular reason for not using boost::swap here?

**Comment by joaquintides** [comment]
Hi,

No, there's no particular reason why ADL-enabled `swap` is not used, and in fact the current behavior is in disagreement with [[swappable.requirements]](https://eel.is/c++draft/swappable.requirements). Will fix this in a few days.

**Comment by valziegler** [comment]
Thank you!

**Comment by joaquintides** [comment]
Fixed in 3caea31bfc4659a755650e2b0d846569b2227939, care to check?

**Comment by valziegler** [comment]
adl_swap works for me, thanks again.
