### ISSUE TITLE
Invalid characters in docs

### ISSUE THREAD

**Issue by Lastique** [boostorg/multi_index#31]
For example, on [this](https://www.boost.org/doc/libs/1_72_0/libs/multi_index/doc/reference/indices.html#complexity_signature) page, there are three question mark characters in places where an ellipsis (...) would be expected.

**Comment by joaquintides** [comment]
Ouch, thanks for reporting! I wonder how these have gone unnoticed by me for so long.

Have you spotted weird chars anywhere else?

**Comment by Lastique** [comment]
No, but I wasn't looking. Those are just the ones I spotted while skimming through that page. If there's an invalid character sequence in the docs source, it might be with doing a search for it.

**Comment by joaquintides** [comment]
Fixed in c9a21d79d6aef4fcc90f53a55d569d0945803fb3.
