### ISSUE TITLE
Error static_cast

### ISSUE THREAD

**Issue by Swierzewski** [boostorg/multi_index#76]
Hello, I have the following error in Visual Studio 2022 with C++20  (it compiles with C++17): 

1>boost\multi_index\detail\node_handle.hpp(155,12): error C2760: syntax error: 'static_cast' was unexpected here; expected 'type specifier'
1>(compiling source file 'configs/file.cxx')
1>    boost\multi_index\detail\node_handle.hpp(155,12):
1>    the template instantiation context (the oldest one first) is
1>        boost\multi_index\detail\node_handle.hpp(46,7):
1>        while compiling class template 'boost::multi_index::detail::node_handle'

The line is 155 is the following : 
private:
  BOOST_MOVABLE_BUT_NOT_COPYABLE(node_handle)

  template <typename,typename,typename>
  friend class boost::multi_index::multi_index_container;

  node_handle(Node* node_,const allocator_type& al):node(node_)
  {
    ::new (static_cast<void*>(allocator_ptr())) allocator_type(al);
  }

Someone already had a similar error and can help me ?

**Comment by joaquintides** [comment]
Hi @Swierzewski, I can't seem to reproduce any such problem locally (VS 2022 Version 17.2.3). Can you provide a minimal reproducible example of the error? Unfortunately, Compiler Explorer seems not to be able to include Boost headers currently, so I'm afraid well have to make do with an offline code snippet, I'll see how I can locate an appropriate VS version to try it out.

Thank you,
